controller_manager:
  ros__parameters:
    update_rate: 10 # Hz

    leg_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

leg_controller:
  ros__parameters:
    joints:
      - base2link1
      - link12link2
      - link22link3

    command_interfaces:
      - position

    state_interfaces:
      - position

    # open_loop_control: true
    # allow_integration_in_goal_trajectories: true
